### PR TITLE
Change MRGP code

### PR DESCRIPTION
**Pull request by aboisbunon**
Hello!
Here is a proposition to take the following user-specified parameters into account for MRGP (with names following sklearn for the Python interface):
* maximum number of threads/n_jobs
* maximum training time (in seconds)
* specific seed/random_state.

Best regards,
AB

### CODE REVIEW

**Comment by lacava** [comment]
thanks! will review.

**Comment by lacava** [comment]
hi @aboisbunon , would you mind re-merging the upstream master? just fixed some versioning conflicts that popped up (#56)

**Comment by aboisbunon** [comment]
Hi @lacava , no problem, it's done. Let me know if you need anything else!

**Review by lacava — APPROVED** [review]
i'm confused as to why this time_out change is not already in the repo... @athril added a time_out parameter a few months ago, and we discussed removing the fixed time limit, but it looks like he only committed the .jar and .py file changes (89206f9bbc49c23f89f25a2b1243d88c4a27aa5f). anyway, these look good.

**Pull request merged**
