### PR TITLE
Webpage with dynamic plots of the results

### PR DESCRIPTION
**Pull request by folivetti**
This pull request adds:

- pages with introductory text and results as dynamic plots made with Vega (docs folder)
- scripts to generate the required CSV files (postprocessing/genCSVs.py and postprocessing/paretoCSVs.py)

Whenever you generate a new results just run both python scripts and commit the CSV files in docs/csv, the plots will be then be updated.

### CODE REVIEW

**Review by lacava — CHANGES_REQUESTED** [review]
- Not sure why docs/postprocessing/tradeoff.md is separated from the index. This will keep it from rendering when users navigate to the post-processing directory. can we put them back together?
- the .md files in docs/ repeat a lot of text from the readmes. I'm wondering if there is any way to avoid having two copies. if the answer is no then so be it. 
- paretoTimeSize.json and the figure should be removed; I don't see its value. I also think it is calculating the Pareto front in reverse w.r.t. training time.
-  It looks awesome otherwise!

**Comment by folivetti** [comment]
Hi @lacava 

- actually I forgot to remove the docs/postprocessing folder entirely, I have remodeled the page so that we have one page for each section https://folivetti.github.io/srbench/  so that the browser won't have to load too many plots at once. I just removed it.
- I just checked and we cannot use `{% include %}` command from a file outside the docs folder. I'll investigate if there's any way to do that.
- done
- :-)

**Comment by folivetti** [comment]
Hi @lacava , I don't know if the pull request needs an action from me, but I think the above requests are already commited to this PR (anything I commit any change, it's automatically incorporated into the PR)

**Comment by lacava** [comment]
hi @folivetti sorry for the delay. these look great. The only thing that looks off is the  https://folivetti.github.io/srbench/datasets/ page. The feynman datasets in PMLB should all be 100,000 samples and the strogatz problems have 400 samples. I think datasets_info.csv may be incorrect; check https://epistasislab.github.io/pmlb/

**Comment by folivetti** [comment]
@lacava found the issue, I was using npoints instead of nsamples. It should be fixed now!

**Pull request merged**
